### PR TITLE
Fixed appveyor test

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by JohanMabille** [comment]
@SylvainCorlay I don't understand why it cannot install dependencies of the wheel from pip while they are available (last build fails on pygments but if you remove the installation of jedi from pip, it will complain that it cannot find jedi).

**Comment by SylvainCorlay** [comment]
@JohanMabille it may be due the fact that we use the `--find-links` option instead of explicitly installing the wheel file.

**Comment by JohanMabille** [comment]
You mean that it would be broken on Windows? We use the same option on Linux and it works like a charm.

**Comment by SylvainCorlay** [comment]
Let's drop Python 3.8 for now. Appveyor does not include it in the base image yet.

**Comment by SylvainCorlay** [comment]
CF https://github.com/appveyor/ci/issues/3329

**Pull request merged**
