### PR TITLE
Added CI

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
You may want to do

```
git update-index --add --chmod=+x io/travis/build-wheels.sh
git commit -m 'Make build-wheels.sh executable'
git push
```

**Comment by SylvainCorlay** [comment]
weird, the scipt appears to be python3 only

**Comment by SylvainCorlay** [comment]
Now we just need to install scikit-build in the docker.

**Comment by SylvainCorlay** [comment]
Maybe a requirement-dev.txt listing skibuild would work. I don't know the minimal version of Python that supports it but all the python3 versions that we support have it.

**Comment by JohanMabille** [comment]
It's already in it, I don't understand why it does not install skbuild when I install cmake first.

**Comment by JohanMabille** [comment]
It seems that the cmake wheel needs cmake to build. So lt's remove it and try to install a decent version of cmake on the system (by default, cmake 2.6 is installed ....)

**Comment by SylvainCorlay** [comment]
It does not seem that the `nlohmann_json` package provides a `nlohmann_json` target unfortunately, but a `nlohmann::json` one instead.

**Comment by JohanMabille** [comment]
I think it does provide a `nlohmann_json` target, see its [CMakeLists.txt](https://github.com/nlohmann/json/blob/develop/CMakeLists.txt). The `find_package` is not wrapped in the xtl, so the issue might come from here.

**Comment by SylvainCorlay** [comment]
Ah, ok, I thought that it was an alias problem.

**Comment by SylvainCorlay** [comment]
`-ldl`

**Comment by JohanMabille** [comment]
I know

**Comment by SylvainCorlay** [comment]
I know that you know

**Comment by JohanMabille** [comment]
But I didn't know that you knew that I knew

**Comment by SylvainCorlay** [comment]
> But I didn't know that you knew that I knew

me neither

**Comment by JohanMabille** [comment]
`XEUS_PYTHON_INSTALL_PATH`? `XEUS_PYTHON_INSTALL_BINDIR`?

**Comment by SylvainCorlay** [comment]
> XEUS_PYTHON_INSTALL_PATH? XEUS_PYTHON_INSTALL_BINDIR?
> XPYTHON_INSTALL_BINDIR? XPYTHON_INSTALL_DIR?

None of these since it will be understood as something that impacts the installation directory.

I would go with `XPYTHON_KERNELSPEC_PATH` or somethinge like this.

**Comment by SylvainCorlay** [comment]
Is our vendored openssl installed at all with scikit-build?

**Comment by SylvainCorlay** [comment]
Note: trying to build locally. I am seeing

```
 /bin/mkdir -p '/usr/share/bash-completion/completions'
 /usr/bin/install -c -m 644 bash-completion/uuidgen '/usr/share/bash-completion/completions'
/usr/bin/install: cannot remove '/usr/share/bash-completion/completions/uuidgen': Permission denied
```

**Comment by JohanMabille** [comment]
Tha is weird, I've never seen that locally. And the OpenSSL libraries are correctly installed (locally).

**Comment by SylvainCorlay** [comment]
so we are missing a setup.py dependency to jedi?

**Comment by JohanMabille** [comment]
and pigments. I'm adding them.

**Pull request merged**
