### PR TITLE
Build Python 3.11 and MacOS arm64

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
Working!

image

**Comment by blink1073** [comment]
Man, that was a crash course in cmake...

**Comment by martinRenou** [comment]
Thanks a lot for looking into this!

**Comment by blink1073** [comment]
Okay, I verified the last works, this is ready for review.

**Comment by blink1073** [comment]
Well that's annoying, `pip._internal.exceptions.UnsupportedWheel: xeus_python-0.14.3-cp311-cp311-macosx_12_0_x86_64.whl is not a supported wheel on this platform` on a 12.0 macos system...

**Comment by blink1073** [comment]
Well that's annoying, `pip._internal.exceptions.UnsupportedWheel: xeus_python-0.14.3-cp311-cp311-macosx_12_0_x86_64.whl is not a supported wheel on this platform` on a 12.0 macos system...

**Comment by blink1073** [comment]
I'd like to follow this up by bumping the xeus python version to 0.15.0 and cutting a release, does that sound good?

**Comment by martinRenou** [comment]
That'd be great! Thanks a lot for doing this

**Review by martinRenou — APPROVED** [review]
Thank you!

**Comment by martinRenou** [comment]
Just pushing a tag to master will trigger a publish of the wheel automatically

**Pull request merged**
