### PR TITLE
Bump to 0.15.0

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
@JohanMabille I'm out of my depth on this one.  😅

**Comment by JohanMabille** [comment]
@blink1073 thanks for opening this, I totally forgot to update the wheel. I think you need to keep all the previous dependencies (including cppzmq and libzmq), and simply add the xeus-zmq package (between xeus and xeus-python); and of course bump the release versions of the xeus packages like you did.

**Comment by blink1073** [comment]
It seems like there's some more cmake magic to do.  I tried mucking around locally with `include_directories` and `link_directories` but couldn't figure it out.

```
   CMake Error at _skbuild/macosx-10.16-x86_64-3.7/cmake-build/_deps/xeus_zmq-src/CMakeLists.txt:88 (find_package):
    By not providing "Findxeus.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "xeus", but
    CMake did not find one.

    Could not find a package configuration file provided by "xeus" (requested
    version 3.0.0) with any of the following names:

      xeusConfig.cmake
      xeus-config.cmake

    Add the installation prefix of "xeus" to CMAKE_PREFIX_PATH or set
    "xeus_DIR" to a directory containing one of the above files.  If "xeus"
    provides a separate development package or SDK, be sure it has been
    installed.
  Building wheel for xeus-python (pyproject.toml): finished with status 'error'
```

**Comment by JohanMabille** [comment]
That's weird, the cmake install files of xeus should be available, I will investigate over the week end

**Comment by JohanMabille** [comment]
OK got it, a check is missing in xeus-zmq CMakeLists.txt. Sorry for that, fixing it now.

**Comment by blink1073** [comment]
I added libuuid on Linux but it is still complaining about a missing `-fPIC` somewhere:

```
 FAILED: _deps/xeus-python-build/xpython_extension.cpython-37m-x86_64-linux-gnu.so
  : && /usr/bin/c++ -fPIC -Wunused-parameter -Wextra -Wreorder -std=c++14 -O3 -DNDEBUG  -flto -shared  -o _deps/xeus-python-build/xpython_extension.cpython-37m-x86_64-linux-gnu.so _deps/xeus-python-build/CMakeFiles/xpython_extension.dir/src/xpython_extension.cpp.o  _deps/xeus-python-build/libxeus-python.a  -lpthread  _deps/xeus_zmq-build/libxeus-zmq.a  _deps/libzmq-build/lib/libzmq.a  -lrt  /__w/xeus-python-wheel/xeus-python-wheel/_skbuild/linux-x86_64-3.7/cmake-install/lib/libcrypto.a  -lpthread  _deps/xeus-build/libxeus.a  /usr/lib/x86_64-linux-gnu/libuuid.a  /__w/xeus-python-wheel/xeus-python-wheel/_skbuild/linux-x86_64-3.7/cmake-install/lib/libsodium.a  -ldl  -lutil  -lrt && cd /__w/xeus-python-wheel/xeus-python-wheel/_skbuild/linux-x86_64-3.7/cmake-build/_deps/xeus-python-build && /usr/bin/strip /__w/xeus-python-wheel/xeus-python-wheel/_skbuild/linux-x86_64-3.7/cmake-build/_deps/xeus-python-build/xpython_extension.cpython-37m-x86_64-linux-gnu.so
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libuuid.a(libuuid_la-gen_uuid.o): relocation R_X86_64_TPOFF32 against `state_fd.6311' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libuuid.a(libuuid_la-randutils.o): relocation R_X86_64_TPOFF32 against `ul_jrand_seed' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: Nonrepresentable section on output
  collect2: error: ld returned 1 exit status
```

**Comment by JohanMabille** [comment]
Therotically we're supposed to installed it, build it and link with the static lib; that is what this [part of the cmake](https://github.com/jupyter-xeus/xeus-python-wheel/blob/master/CMakeLists.txt#L54) is supposed to do. And I can see it installed in the logs, what I don't understand is why it does not find it when building xeus, this part has not changed since last release (or at least not in a visible way).

**Comment by JohanMabille** [comment]
I cannot reproduce locally, I need to setup a branch and instrument the cmake.

**Comment by SylvainCorlay** [comment]
It seems that the build is linking against a system-install libuuid instead of the one we build statically.

**Comment by blink1073** [comment]
> It seems that the build is linking against a system-install libuuid instead of the one we build statically.

I added an `apt-get install` in [`e3f4e86` (#104)](https://github.com/jupyter-xeus/xeus-python-wheel/pull/104/commits/e3f4e865dde5e2f0e0607245243e538a5ac6de71) because prior to that the error was:

```
  /__w/xeus-python-wheel/xeus-python-wheel/_skbuild/linux-x86_64-3.7/cmake-build/_deps/xeus-src/src/xguid.cpp:20:23: fatal error: uuid/uuid.h: No such file or directory
   #include <uuid/uuid.h>
                         ^
  compilation terminated.
```

**Comment by JohanMabille** [comment]
To summarize:
- libuuid is correctly downloaded, built and installed in the building prefix, i.e. `<something>/cmake-install`.
- the path where cmake searches the headers contains `<something>/cmake-install/uuid` but not `<something>/cmake-install/`
- xeus includes `<uuid/uuid.h>`

The correct fix is to have `<something>/cmake-install/` in the search path for headers.

**Comment by JohanMabille** [comment]
Sooooo we need a release of xeus ;)

**Comment by blink1073** [comment]
Nice work @JohanMabille!

**Comment by blink1073** [comment]
https://pypi.org/project/xeus-python/0.15.0/

**Pull request merged**
